const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
class El { constructor(){this.children=[];this.handlers={};this.value='';} append(...x){this.children.push(...x);} replaceChildren(...x){this.children=x;} addEventListener(e,f){this.handlers[e]=f;} }
const ids=['availability-website-grid','availability-rows','availability-summary','availability-search','availability-filter','availability-pagination','availability-page','availability-prev','availability-next','availability-refresh'];const els=Object.fromEntries(ids.map(id=>[id,new El()]));
const deals=Array.from({length:41},(_,i)=>({id:i+1,title:'Hotel '+String(i+1).padStart(2,'0'),source:'provider_sync',status:'active',approved_at:1,price:100}));
let ready;const done=new Promise(r=>ready=r);
const core={requireAuth:async()=>({role:'superadmin'}),mountShell:()=>{throw Error('Testpreview mag geen beheershell tonen');},request:async path=>({supplier_deal:{provider:'nuitee',environment:'sandbox',supplier_content:{hotel:{name:deals[Number(path.split('/').at(-1))-1].title}}}}),imageUrl:()=>null,money:n=>'€'+n};
const document={getElementById:id=>els[id],createElement:()=>new El(),addEventListener:()=>{}};
const window={AdminCore:core,AdminOfferData:{all:async()=>deals},addEventListener:()=>{},SeasonDealsAvailabilityCatalog:{createCatalog:({render})=>({refresh:async()=>{render([deals[0]],deals.map(d=>({id:d.id,status:d.id===1?'available':'unknown'})));ready();},expire:()=>{},dispose:()=>{}})}};
vm.runInNewContext(fs.readFileSync(__dirname+'/../admin/js/availability-catalog.js','utf8'),{window,document,AbortController,setTimeout,clearTimeout,setInterval:()=>1,clearInterval});
(async()=>{await done;assert.equal(els['availability-website-grid'].children.length,1);assert.equal(els['availability-website-grid'].children[0].children[0].children.at(-1).href,'../nuitee-availability-preview.html?portal=admin&id=1');els['availability-search'].value='no match';els['availability-search'].handlers.input();assert.equal(els['availability-website-grid'].children[0].textContent,'Geen vers bevestigd aanbod voor deze selectie.');console.log('PASS: visitor preview contains only confirmed offer, date link and safe empty state.');})().catch(e=>{console.error(e);process.exitCode=1;});