const assert = require('node:assert/strict');
const {validateRequest,evaluateAvailability} = require('./policy');
const now = Date.parse('2026-10-08T09:00:00Z');
const deal = {id:17,status:'active',approved_at:now,deleted_at:0,price:241.43,minimum_nights:2,travel_period_start:Date.parse('2026-11-10'),travel_period_end:Date.parse('2026-11-12')};
const rate = {name:'Nhow Room',boardType:'RO',boardName:'Room Only',adultCount:2,childCount:0,remarks:'',cancellationPolicies:{refundableTag:'NRFN',cancelPolicyInfos:[]},retailRate:{taxesAndFees:[]}};
const offer = {supplier:'nuitee',supplierId:2,rateType:'package',priceType:'commission',offerId:'ephemeral',offerRetailRate:{amount:201.19,currency:'EUR'},rates:[rate]};
const supplier = {provider:'nuitee',environment:'sandbox',supplier_hotel_id:'lp225fcf',supplier_mapping:{request:{currency:'EUR',guest_nationality:'NL',occupancies:[{adults:2}]},offer},pricing_config:{processing_fee:1.30,stripe_fee_percentage:3,stripe_fee_fixed:.25,min_margin_amount:20}};
const input = {checkin:'2026-11-10',checkout:'2026-11-12',guests:2};
const search = {success:true,data:[{hotelId:'lp225fcf',roomTypes:[offer]}]};
assert.equal(validateRequest(deal,supplier,input,now).valid,true);
for (const change of [{checkin:'2026-02-30'},{checkout:'2026-11-10'},{checkin:'2026-11-09'},{guests:1}]) assert.equal(validateRequest(deal,supplier,{...input,...change},now).valid,false);
assert.equal(validateRequest({...deal,status:'draft'},supplier,input,now).valid,false);
assert.equal(validateRequest(deal,{...supplier,environment:'production'},input,now).valid,false);
const result = evaluateAvailability(deal,supplier,search,now);
assert.equal(result.status,'available');
assert.equal(result.customer_price,241.43);
assert.equal(result.margin_after_reserve,31.44);
assert.equal(result.quantity,null);
assert.equal(result.can_pay,false);
assert.equal(evaluateAvailability(deal,supplier,{success:false},now).status,'unknown');
assert.equal(evaluateAvailability(deal,supplier,{success:true,data:[]},now).status,'unavailable');
function withOffer(o) {return {success:true,data:[{hotelId:'lp225fcf',roomTypes:[o]}]};}
assert.equal(evaluateAvailability(deal,supplier,withOffer({...offer,offerRetailRate:{amount:230,currency:'EUR'}}),now).status,'price_blocked');
assert.equal(evaluateAvailability(deal,supplier,withOffer({...offer,offerRetailRate:{amount:201,currency:'USD'}}),now).status,'unknown');
assert.equal(evaluateAvailability(deal,supplier,withOffer({...offer,rates:[{...rate,boardType:'BB'}]}),now).status,'unavailable');
assert.equal(evaluateAvailability(deal,supplier,withOffer({...offer,rates:[{...rate,cancellationPolicies:{refundableTag:'RFN'}}]}),now).status,'unavailable');
const localOffer = {...offer,rates:[{...rate,retailRate:{taxesAndFees:[{amount:12.6,currency:'EUR',included:false,description:'City tax'}]}}]};
assert.equal(evaluateAvailability(deal,supplier,withOffer(localOffer),now).status,'conditions_changed');
assert.equal(evaluateAvailability(deal,supplier,withOffer(localOffer),now).local_fees_total,12.6);
const changedCheap = {...localOffer,offerId:'changed-cheap',offerRetailRate:{amount:190,currency:'EUR'}};
const unchangedDearer = {...offer,offerId:'unchanged-dearer',offerRetailRate:{amount:202,currency:'EUR'}};
const multiple = values => ({success:true,data:[{hotelId:'lp225fcf',roomTypes:values}]});
assert.equal(evaluateAvailability(deal,supplier,multiple([changedCheap,unchangedDearer]),now).offer_id,'unchanged-dearer');
assert.equal(evaluateAvailability(deal,supplier,multiple([unchangedDearer,changedCheap]),now).status,'available');
const unchangedUnprofitable = {...unchangedDearer,offerRetailRate:{amount:230,currency:'EUR'}};
assert.equal(evaluateAvailability(deal,supplier,multiple([changedCheap,unchangedUnprofitable]),now).status,'price_blocked');
assert.equal(evaluateAvailability(deal,supplier,multiple([changedCheap]),now).status,'conditions_changed');
assert.equal(evaluateAvailability(deal,supplier,withOffer({...offer,rates:[{...rate,retailRate:{taxesAndFees:[{amount:12.6,currency:'EUR'}]}}]}),now).status,'unknown');
assert.equal(JSON.stringify(deal),JSON.stringify({...deal}));
console.log('Availability policy: date, approval, mapping, provider failure, fixed price, margin, tax and sandbox payment checks passed.');
